services:
  db:
    image: pgvector/pgvector:pg16
    container_name: eduvision_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adaptive_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: eduvision_core
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/adaptive_core
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_MODEL=${TOGETHER_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - SECRET_KEY=${SECRET_KEY}
      - USE_LLM_FOR_SUMMARY=${USE_LLM_FOR_SUMMARY}
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
